version: "2"

issues:
  uniq-by-line: true

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
    checkstyle:
      path: golangci-lint-report.xml
  sort-order:
    - file
    - linter
    - severity
